[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "MEA-Absorption-Column"
version = "0.1.0"
description = "A Python based MEA Absorption Column model"
readme = "README.md"
license = {text = "MIT"}
authors = [{ name = "Tanner Polley", email = "tannerwpolley@gmail.com" }]
requires-python = ">=3.13,<3.14"
dependencies = [
    "epcsaft @ file:///home/tnnrpolley21/Workspaces/Engineering/ePC-SAFT-local-state/artifacts/objects/sha256/f6e5b51dad79741c759393688f7daa547c9eb73f5944d5f877b3b32b1e56714a/epcsaft-0.2.0.dev0-cp313-cp313-linux_x86_64.whl",
    "matplotlib>=3.8",
    "numpy>=1.26",
    "openpyxl>=3.1",
    "pandas>=2.1",
    "scipy>=1.11",
]

[dependency-groups]
test = [
    "pytest>=8.0",
]
dev = [
    { include-group = "test" },
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
mea_absorption_column = [
    "data/*.csv",
    "data/epcsaft_neutral/*.json",
    "data/epcsaft_datasets/*/*.json",
    "data/epcsaft_datasets/*/pure/*.csv",
    "data/epcsaft_datasets/*/mixed/binary_interaction/*.csv",
    "data/epcsaft_datasets/*/mixed/rel_perm/*.csv",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
addopts = "-ra"
testpaths = ["tests"]
