{
  "project": {
    "pre-render": "python3 manuscript.py prepare"
  },
  "execute": {
    "enabled": true,
    "daemon": false,
    "cache": true,
    "echo": false,
    "warning": false,
    "error": false
  },
  "format": {
    "html": {
      "embed-resources": false
    }
  }
}
